### ISSUE TITLE
Question section mismatch

### ISSUE THREAD

**Issue by skydrome** [shuLhan/rescached-legacy#2]
im getting these errors on domain lookups

dig www.isup.me @127.0.0.1 
;; Question section mismatch: got www.isup.me/AAAA/IN

dig mail.google.com 
;; Question section mismatch: got mail.google.com/AAAA/IN

**Comment by shuLhan** [comment]
I got that too. Especially after running an application with an extensive network connection, like torrent.

I will look into it, when I have some extra time.

Thanks.

**Comment by skydrome** [comment]
no biggie, just gonna switch back to pdnsd for the time being. Id just like to say that i think rescached is faster and a nicer alternative to pdnsd :)

**Comment by shuLhan** [comment]
Last commits fix this. Please try it again before I can close it.
