### ISSUE TITLE
hosts file newline

### ISSUE THREAD

**Issue by skydrome** [shuLhan/rescached-legacy#8]
Just in case anyone else comes across this issue and hopefully prevents some hair from being ripped out.

If your /etc/hosts file does _not_ have a newline at the end
`
Rescached: loading host file '/etc/hosts'
Cannot allocate memory
`
Maybe rescached can check for this condition and give the reason in the future

**Comment by shuLhan** [comment]
Thanks for the report, I will check it out.

**Comment by shuLhan** [comment]
I have tested on my local machine (by default my `/etc/hosts` does not have newline) and no error. Can you share you hosts file? Send it to my email [1] if your hosts maybe contains some private IP

[1] ms@kilabit.info

**Comment by skydrome** [comment]
Ok here are my three examples i am encountering, its not a special hosts file or large. Happens with just a single entry. 
ps. Did you check that your text editor doesnt automatically add a newline on filesave?

single entry with newline
`1. 127.0.0.1 localhost`
`2. <newline>`
> Rescached: loading host file '/etc/hosts'
Rescached: 1 addresses loaded.

first line is empty
`1. <blank>`
`2. 127.0.0.1 localhost`
> Rescached: loading host file '/etc/hosts'
Rescached: 0 addresses loaded.


single entry no newline
`1. 127.0.0.1 localhost`
> Rescached: loading host file '/etc/hosts'
*** Error in `rescached': malloc: top chunk is corrupt: 0x0ec44ae8 ***
[1]    23646 abort      sudo rescached /etc/rescached/rescached.cfg


two or more entries no newline
`1. 127.0.0.1 localhost`
`2. 127.0.0.1 localhost.localdomain`
> Rescached: loading host file '/etc/hosts'
*** Error in `rescached': free(): invalid pointer: 0x123f5660 ***
Cannot allocate memory
[1]    27494 segmentation fault  rescached /etc/rescached/rescached.cfg



My system is Arch i686
gcc (GCC) 7.2.0
unset CXXFLAGS before make

**Comment by skydrome** [comment]
single entry no newline running in gdb gives

> Rescached: loading host file '/etc/hosts'
Program received signal SIGSEGV, Segmentation fault.
0xb7f05943 in __memmove_ssse3 () from /usr/lib/libc.so.6

if that means anything to you
I ran `make debug` but still dont get symbol information for `bt full`
